channels:
  - pytorch
  - fastai
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip

  - pytorch
  - timm
  - wandb

  - pandas
  - scikit-learn==0.19.0
  - matplotlib
  - numpy
  - rich
  - typer
  - opencv
  - ttach

  - black
  - isort
  - flake8
  - flake8-bugbear
  - mypy
  - ipywidgets
  - pre-commit

  - pip:
      - grad-cam
